### ISSUE TITLE
clean up documentation for building NEML

### ISSUE THREAD

**Issue by lynnmunday** [idaholab/blackbear#107]
## Bug Description
Clarify steps needed for building blackbear with NEML

## Steps to Reproduce
https://mooseframework.org/blackbear/source/materials/NEMLStress.html
and "&&" in the git command.  Inidicate where to add --with-boost flag for rebuilding libmesh
Do I need to make one of these if I just want to update documentation?  

## Impact
annoyance

**Comment by bwspenc** [comment]
@lynnmunday Sometimes we have catch-all issues open for things like documentation, but if not, making one for a specific issue is great, especially if it's about an error in the documentation.

It looks like some of the text that's supposed to show up as computer commands isn't showing up right either on that page.  That would be great if you can clean that up.

**Comment by lynnmunday** [comment]
@bwspenc   I"ll do that next time, I see issue 2 is for documentation.

**Comment by bwspenc** [comment]
Yeah, either way is fine.  In general, we should probably lean toward working with more specific issues, so definitely use this issue for what you will fix here.
