### ISSUE TITLE
accelerate LAROMANCE

### ISSUE THREAD

**Issue by hugary1995** [idaholab/blackbear#159]
Right now ADLAROMANCE is very slow.

I have a large deformation model, using AD and elastic stress, the first two steps take 18.217 seconds.
If I switch to an AD temperature dependent power law creep, the first two steps take 20.671 seconds.
Now if I switch to the AD P91 LAROMANCE creep model, the first two steps take 87.502 seconds.

I know this is not exactly an apples-to-apples comparison, but there is definitely a lot of space for improvement.

**Comment by hugary1995** [comment]
NonAD models are way faster:

|  | elastic | power law creep | LAROMANCE |
| ------------- | ------------- | ---------------- | ----------|
| non-AD  | 3.585 | 4.353 | ??? |
| AD | 18.217 | 20.671 | 87.502 |

There seems to be a consistent slow down factor for AD.

**Comment by bwspenc** [comment]
Thanks for looking into this! Hold off on posting the LAROMANCE inputs, but could you maybe put up a branch that has the other three test cases for people to look at?

**Comment by bwspenc** [comment]
This is really a MOOSE framework/modules issue rather than BlackBear, I guess.

**Comment by hugary1995** [comment]
You are right. I opened a discussion at [https://github.com/idaholab/moose/discussions/16466](https://github.com/idaholab/moose/discussions/16466).
