### ISSUE TITLE
Get rid of deprecated usage of declarePropertyOld()

### ISSUE THREAD

**Issue by bwspenc** [idaholab/blackbear#19]
It has been replaced by getMaterialPropertyOld()

**Comment by permcody** [comment]
Well almost. Note that declarePropertyOld may still be necessary if there
is a true material old dependency (within the material itself).

**Comment by bwspenc** [comment]
Really?  I thought it was replaced even in that case. What happens if you use getMaterialPropertyOld() within the material itself?

**Comment by permcody** [comment]
Well perhaps I am mistaken. @rwcarlsen, is my statement correct?

**Comment by bwspenc** [comment]
The PR I just submitted replaces some usages of it within the material itself, and passes the tests fine. We've been doing this all over the place.  Look for example at _stress_old in ComputeFiniteStrainElasticStress.C (in tensor_mechanics).

**Comment by rwcarlsen** [comment]
@permcody - declarePropertyOld should never be necessary.  If you need the old property in the same material that provides the not-old property, you just use getMaterialPropertyOld instead.

**Comment by permcody** [comment]
OK - good to know!
