### ISSUE TITLE
Cleaning input files using ConcreteThermalMoisture

### ISSUE THREAD

**Issue by jain651** [idaholab/blackbear#256]
## Reason

A PR is pending to update the ConcreteThermalMoisture class, that will remove the moisture capacity material property for Mensi and Bazant moisture models. Therefore changes in the input files are required before the codes changes can be merged in. 

## Design

Removal the `moisture_capacity` auxVariable and `rh_capacity` auxkernel from the input files. 

## Impact

There will not be any changes in the features, however there is a need to changes the csv and exodus files for some tests.

**Comment by bwspenc** [comment]
Thanks!  Just FYI, we probably don't really need a separate issue for this since this falls in support of the other things you're working on.
