### ISSUE TITLE
Update NEML submodule

### ISSUE THREAD

**Issue by dschwen** [idaholab/blackbear#289]
## Reason
New models have been added to NEML since the last update 5 months ago and we need those for a project.

## Design
Update submodule, verify that tests work.

## Impact
Added capability.

**Comment by dschwen** [comment]
darn

```
dyld[94111]: symbol not found in flat namespace '__ZN4neml10Quaternion10initializeERNS_12ParameterSetE'
```

that's `_neml::Quaternion::initialize(neml::ParameterSet&)`

**Comment by dschwen** [comment]
That function is nowhere to be found...

**Comment by dschwen** [comment]
weird, this class

```
class NEML_EXPORT CrystalOrientation : public NEMLObject, public Orientation { 
 public:
  CrystalOrientation(ParameterSet & params);

  /// Type for the object system
  static std::string type();
  /// Parameters for the object system
  static ParameterSet parameters();
  /// Setup from a ParameterSet
  static std::unique_ptr<NEMLObject> initialize(ParameterSet & params);
};
```

derived form Quaternion and NEMLObject and has an initialize method. But why does the dynamic linker assume that method should exist on the Quaternion class?

**Comment by reverendbedford** [comment]
`Quaternion` is no longer supposed to be accessible from the XML input system, just `CrystalOrientation`.  

Is this just in compiling NEML?  Or linking to blackbear?  I've been using the current version of NEML with our app and haven't run into any issues and we do test the build on Windows, Mac, and Linux.

**Comment by dschwen** [comment]
This is a runtime linker error that pops up  when executing Blackbear (`./blackbear --json`)

**Comment by reverendbedford** [comment]
Are you working from `devel`?  Because if so I can't even get to the point where I might be helpful...

```
/home/messner/projects/blackbear/src/auxkernels/MineralDissolutionPrecipAux.C:77:28: error: ‘_u_old’ was not declared in this scope; did you mean ‘_dt_old’?
   77 |   Real _new_mineral_conc = _u_old[_qp] - kinetic_rate * _dt;
```

**Comment by dschwen** [comment]
Ok, hang on, I wonder if this was a simple error due to lingering objects that I should have clobbered first...

**Comment by dschwen** [comment]
🤦  yeah, that was it
