### ISSUE TITLE
Add capabilities to test ConcreteExpansionEigenstrainBase

### ISSUE THREAD

**Issue by agiorla** [idaholab/blackbear#38]
We need a way to test features implemented in the `ConcreteExpansionEigenstrainBase` class without having to rely on the more elaborate `ConcreteASREigenstrain` model.

**Comment by agiorla** [comment]
@bwspenc This was actually done in the PR #39 (I probably forgot the `close` statement in the initial commit), so this can probably be closed ;)

**Comment by bwspenc** [comment]
OK, thanks.  Closing.
