### ISSUE TITLE
Coupled ConcreteExpansionEigenstrainBase with MazarsDamage

### ISSUE THREAD

**Issue by agiorla** [idaholab/blackbear#43]
The `ConcreteExpansionEigenstrainBase` class needs to propose an option to be coupled with the `MazarsDamage` class. The option should exhibit the following features:
- Unconfined expansion causes damage.
- Confined expansion causes additional damage, so that the apparent expansion remains null when the external stress is higher than `sigma_u`.
- The apparent loss of tensile/compressive strength is not proportional to the loss of elasticity (it is lower)

**Comment by agiorla** [comment]
@bwspenc I am going to integrate the functionalities from ConcreteASRElasticityTensor inside the ConcreteExpansionEigenstrainBase class (that will essentially be able to set up a damage MaterialProperty<Real> which can be, in turn, used either as an input for the ScalarDamage class, or as an optional input for the Mazars model).

Should I remove the files related to ConcreteASRElasticityTensor, or would you prefer to keep it there?

**Comment by bwspenc** [comment]
I guess I need to understand better what you are planning to do. ConcreteASRElasticityTensor currently decreases E as a function of ASR extent. If I understand correctly, it sounds like you want to represent that effect through damage. If that's the right way to do that, then I would say that we should delete ConcreteASRElasticityTensor.

**Comment by bwspenc** [comment]
That makes sense.  Representing a loss of stiffness is what damage models do.

**Comment by agiorla** [comment]
I am currently writing a scalar damage model that combines an arbitrary number of scalar damage models. Do you think this would go better in MOOSE or in BlackBear?
