### ISSUE TITLE
Use Absolute Path for NEML Submodule?

### ISSUE THREAD

**Issue by herter4171** [idaholab/blackbear#97]
## Bug Description

Right now, the NEML submodule is a relative path in `.gitmodules`.  To the untrained eye, this makes the repo appear to be missing when working with a fork not hosted on public GitHub.

## Steps to Reproduce

Use the repo with an origin other than pubic GitHub.
## Impact

We have an internally hosted BLACKBEAR repo on our GitHub Enterprise deployment at Kairos Power that mostly parallels INL's.  I've already put the NEML submodule path as absolute there, and I'd just like to avoid any potential conflict when pulling in fresh INL code, e.g. a repo maintainer breaking stuff by accidentally switching back to the relative path version of the `.gitmodules` file.

## PS
I'll submit a PR on this, then see what happens.

**Comment by bwspenc** [comment]
OK, that makes sense. I made it relative because that makes it so that if you cloned using ssh, it would use the ssh address automatically to pull in the submodule. If this is giving you grief, though, probably better to switch to an absolute path -- that's just a minor convenience thing.
